apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bamu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-bamu
    app.kubernetes.io/part-of: image-repository-cr-dotnet-component
  name: devfile-sample-dotnet60-basic-bamu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bamu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-bamu
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-yldm-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-bamu@sha256:4708d94d6872bf47a7901e81b78314cbd9084281907da851d59980b2bf592170
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
